version: '3.8'

services:
  # Backend
  healthphone:
    image: kendallrc/healthphone:latest  # Cambia esto a tu imagen en Docker Hub
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    links:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password   
      MYSQL_DATABASE: Healthphone           
      MYSQL_USER: user                    
      MYSQL_PASSWORD: password            
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql         
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
