version: '3'

services:
  # Backend Django (API REST)
  healthphone:
    build:
      context: ../python  
    command: gunicorn drf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../python/django:/app   
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    links:
      - mysql
  
  # MySQL Database
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password   
      MYSQL_DATABASE: Healthphone           
      MYSQL_USER: user                    
      MYSQL_PASSWORD: password            
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql         
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "3306"  

volumes:
  mysql_data: