name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa un runner de GitHub con Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker-compose -f ./Healthphone/docker/docker-compose.yml up -d --build
