name: Deploy Django App

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: kendallrc  # Define en Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Define en Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker  # Asegúrate que apunte al docker-compose correctamente
          push: true
          tags: kendallrc/healthphone:latest

      - name: Deploy to Server
        env:
          SSH_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEAshej/Q5fiJwIv18Ym+PLEf2VR6L2tOzDH6F8o2hbwiBOGsg8MBGF
            0YolsY3/CYr+ecxX//yIKNqcOm4uyumoEdogE9wXw4HhouU4GjuG8qWczzgLez7zozsgfS
            4t6Kfx3ZEDKq3agAn+saYU3KCZlfry8hjt1kNI3VQQ7wx1M2PErNTJdWcSkiRAqVxQ7M7v
            AZo/VSaaXHRU7SvUjjrabdmUv1jiCipQKd/3P1QLLgrlwqXS55AzIVV85zG8jPzbU+xC3K
            BW7TM1EtwevKP6optCm7fmhBv7bl7lizV/KnMdoo4/X431e+Amzcbs/b6stEOA0xxdu3sZ
            5lHhbeGMyokSC5RBOT8dzxCeQDTMuswfZp9Jwjcid+aq0bUKHo7u9uIxdKJcKjN5tnKWQL
            uKRa6rzHYJwTM0lhsRTGFpC0ZKHoJONBcqjFLnnlBpYzdNJiiYJdETwISHbUpcuf6Ypwu4
            c0ANmwr4KhVnRbt6suFXgPAwR2lQhnlu2ozRDQVvAg7lSjhf/S7Q4BNYDedGtUptQO7oaf
            yCueLootWvoJkRhatHhC6xJBvDLou8q6A3VUumtGDRdUTZwErimJ18g9QB2RBwdiTyE6R0
            Xu6fvPj9ZOeCmOS38KkGwhYqNTFihM4FCEXOgezJpOda/s/h9Q2n9n/E7/I7z37Wtwgapd
            UAAAdIHP9KWxz/SlsAAAAHc3NoLXJzYQAAAgEAshej/Q5fiJwIv18Ym+PLEf2VR6L2tOzD
            H6F8o2hbwiBOGsg8MBGF0YolsY3/CYr+ecxX//yIKNqcOm4uyumoEdogE9wXw4HhouU4Gj
            uG8qWczzgLez7zozsgfS4t6Kfx3ZEDKq3agAn+saYU3KCZlfry8hjt1kNI3VQQ7wx1M2PE
            rNTJdWcSkiRAqVxQ7M7vAZo/VSaaXHRU7SvUjjrabdmUv1jiCipQKd/3P1QLLgrlwqXS55
            AzIVV85zG8jPzbU+xC3KBW7TM1EtwevKP6optCm7fmhBv7bl7lizV/KnMdoo4/X431e+Am
            zcbs/b6stEOA0xxdu3sZ5lHhbeGMyokSC5RBOT8dzxCeQDTMuswfZp9Jwjcid+aq0bUKHo
            7u9uIxdKJcKjN5tnKWQLuKRa6rzHYJwTM0lhsRTGFpC0ZKHoJONBcqjFLnnlBpYzdNJiiY
            JdETwISHbUpcuf6Ypwu4c0ANmwr4KhVnRbt6suFXgPAwR2lQhnlu2ozRDQVvAg7lSjhf/S
            7Q4BNYDedGtUptQO7oafyCueLootWvoJkRhatHhC6xJBvDLou8q6A3VUumtGDRdUTZwEri
            mJ18g9QB2RBwdiTyE6R0Xu6fvPj9ZOeCmOS38KkGwhYqNTFihM4FCEXOgezJpOda/s/h9Q
            2n9n/E7/I7z37WtwgapdUAAAADAQABAAACAAg7KXwnruisdYcKySNjWt5g/wZJlOd1zern
            VtBioWMOhS2dtZJvLOUrYmSbcH8rammMtUCClnR07iWRNB5ywC7bCwJ/+KUzmo8h0v77Y1
            hRqTa2m2k91prjv7Opb7vCD16zNhdB48hpLdleGLa9wXt6FsJzvoJZp8N7ADFcPQp8APoP
            96OyeNxCSq7JMoBPbCKB042G9Dlzsv0nOnK8a54KIWLao8/edsgIru/BXabqIAZoDaBgPM
            y8m8I/vTwy75woXkq+KmZaKIjPnagQWCQt0t1JmaDffjZysl9FwLPgkC0UL/+lmwP3rzNx
            j0CHEIpgWFLpi7d/kAniHO4sL4qVHz9uYvdLKD9Fj76eSPLUmNbqiqae5oDSH1mAEMciak
            NR9golDpPDmPw1SxRFseM6ZNDWLgK5nvYqNhFo6j32Jezr4Ynsab5oeZ8pvG+x+RYQIuxm
            mxzmLBysOnnm8YWGrsiBySm0WENm5tbMQ30bbahNo9X+2yHNAVb3+7DhjWDy4u7NJ2MWS9
            xQD1SbMDYiY5y+nqMSNAkDiD5nSYGbPyCqXEkgvpX0ro3p2iR2hr5+aETzZadNXLoz9DJu
            HP0GDqr1s3j2Dadtrn17bYMWG1oAoFYuac6wyfqCYVzo8pOSZ3lWBRqqTsZVdNASLlegJn
            pCgGvxprAKhhU6/d0dAAABAFgud/Gg2PK9Z43n2iynEB9il8fbgY4qua5/3fWhcBEiwft1
            tXpLxi6rB6K2yRyAY36JuvBdqqofFpTk+yVGxEsq0t+lXjKWl71C3DlamvmEmALqsBjUy1
            zAd6cgVu3pOB8SYH5sLXB1Uw8HQt32CEyLcSrpnpX+jc+oVlBnKTBkmtvRM0jzX5WiPyr6
            ASqiTbKWmh7NHdNxP2PoCz7OOvhge4aC+GvspYMQtwl4wP3wnuheNFU3X50zyiQ87UrNH1
            06E+Mrh4yyxg0nsap/ZuoGNbPe+EjcZlLKeET/lui3uLhOXTrmazE5geH8tKaGCtrfPYTU
            JpnzIM/e28gCqO0AAAEBANo3FZph7Emykej54UNTDUD5nmtZMX/3epolkgILFonwd3eew8
            TzLJzFPqkhcz+v/NfK4bCAQBgVWPkqfKYBPql6p69I7UF9Ono1udlyUAVIakdB0vpj9gbf
            0/hG+dP4aIkFzS139fsu8uvPV9ikVCda3b7ZJq4gTySkYPyfZkHaA1V3aboxxIrYdYvfO2
            2CKNa4KPvsxjCJiEz8j6Tv8ZHHg262055N8Zem+D11uSQYPpZLpnZogOSos/FZ0Q0du7hj
            q7jenPoyR5jaG8zAaA8jQ1wyz8LQnokEGroKiD29PZp4QRQF+LiXJrEUhLHM+XGdM8RM3Q
            g4ZuZ1uOjX+GsAAAEBANDuA8h7LQBGm2ggbPhxN22YQiC04g7iqsIRfkptDgD8/7Fzqhht
            D/+cZa1JvG47ZnsXEpRG6dpTEL8qtcl28CkznDJmkk/UzdA9oOfpr1jUeNcHAHmXPRImIg
            oQf+YMIcH5dRbsO4rYMj8f8QEnjxOtuM3EsRx0tBDT8WFQ7xbkps4Pqub3Av/YFFRJA57N
            JFySQvLIHGpDdxg5f1OTvoQOxSyuJQZlgS2bW+GVmvQzn92bAMJh9xQ1etbsOQsNdyMqeQ
            mb7y5qerZVHTEAVYmNCvrt2PVHqSBgW28Q8fmwjzX/PDU2GIJAznumnK9qRrPzkYuo4vy4
            +cbEkt1Uar8AAAARcGMgbGVub3ZvQEtlbmRhbGwBAg==
            -----END OPENSSH PRIVATE KEY-----"  # Agrega una clave SSH privada en Secrets
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY "Pc Lenovo"@192.168.18.168 "
          cd 'C:\Users\Pc Lenovo\OneDrive - Estudiantes ITCR\TEC\II Semestre 2024\Diseño\Proyecto\ProyectoDiseno\Healthphone\Docker' && \
          docker-compose pull && \
          docker-compose up -d
          "
