name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]  # Indica que se usará el runner auto-hospedado

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        run: |
          docker-compose -f ./Healthphone/docker/docker-compose.yml up -d --build
