name: Deploy Django App

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: kendallrc  # Define en Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Define en Secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Healthphone/Backend  # Asegúrate que apunte al docker-compose correctamente
          push: true
          tags: kendallrc/healthphone:latest

      - name: Deploy to Server
        env:
            SSH_KEY: "-----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
              NhAAAAAwEAAQAAAgEAshej/Q5fiJwIv18Ym+PLEf2VR6L2tOzDH6F8o2hbwiBOGsg8MBGF
              0YolsY3/CYr+ecxX//yIKNqcOm4uyumoEdogE9wXw4HhouU4GjuG8qWczzgLez7zozsgfS
              4t6Kfx3ZEDKq3agAn+saYU3KCZlfry8hjt1kNI3VQQ7wx1M2PErNTJdWcSkiRAqVxQ7M7v
              AZo/VSaaXHRU7SvUjjrabdmUv1jiCipQKd/3P1QLLgrlwqXS55AzIVV85zG8jPzbU+xC3K
              BW7TM1EtwevKP6optCm7fmhBv7bl7lizV/KnMdoo4/X431e+Amzcbs/b6stEOA0xxdu3sZ
              5lHhbeGMyokSC5RBOT8dzxCeQDTMuswfZp9Jwjcid+aq0bUKHo7u9uIxdKJcKjN5tnKWQL
              uKRa6rzHYJwTM0lhsRTGFpC0ZKHoJONBcqjFLnnlBpYzdNJiiYJdETwISHbUpcuf6Ypwu4
              c0ANmwr4KhVnRbt6suFXgPAwR2lQhnlu2ozRDQVvAg7lSjhf/S7Q4BNYDedGtUptQO7oaf
              yCueLootWvoJkRhatHhC6xJBvDLou8q6A3VUumtGDRdUTZwErimJ18g9QB2RBwdiTyE6R0
              Xu6fvPj9ZOeCmOS38KkGwhYqNTFihM4FCEXOgezJpOda/s/h9Q2n9n/E7/I7z37Wtwgapd
              UAAAdIHP9KWxz/SlsAAAAHc3NoLXJzYQAAAgEAshej/Q5fiJwIv18Ym+PLEf2VR6L2tOzD
              H6F8o2hbwiBOGsg8MBGF0YolsY3/CYr+ecxX//yIKNqcOm4uyumoEdogE9wXw4HhouU4Gj
              uG8qWczzgLez7zozsgfS4t6Kfx3ZEDKq3agAn+saYU3KCZlfry8hjt1kNI3VQQ7wx1M2PE
              rNTJdWcSkiRAqVxQ7M7vAZo/VSaaXHRU7SvUjjrabdmUv1jiCipQKd/3P1QLLgrlwqXS55
              AzIVV85zG8jPzbU+xC3KBW7TM1EtwevKP6optCm7fmhBv7bl7lizV/KnMdoo4/X431e+Am
              zcbs/b6stEOA0xxdu3sZ5lHhbeGMyokSC5RBOT8dzxCeQDTMuswfZp9Jwjcid+aq0bUKHo
              7u9uIxdKJcKjN5tnKWQLuKRa6rzHYJwTM0lhsRTGFpC0ZKHoJONBcqjFLnnlBpYzdNJiiY
              JdETwISHbUpcuf6Ypwu4c0ANmwr4KhVnRbt6suFXgPAwR2lQhnlu2ozRDQVvAg7lSjhf/S
              7Q4BNYDedGtUptQO7oafyCueLootWvoJkRhatHhC6xJBvDLou8q6A3VUumtGDRdUTZwEri
              mJ18g9QB2RBwdiTyE6R0Xu6fvPj9ZOeCmOS38KkGwhYqNTFihM4FCEXOgezJpOda/s/h9Q
              2n9n/E7/I7z37WtwgapdUAAAADAQABAAACAAg7KXwnruisdYcKySNjWt5g/wZJlOd1zern
              VtBioWMOhS2dtZJvLOUrYmSbcH8rammMtUCClnR07iWRNB5ywC7bCwJ/+KUzmo8h0v77Y1
              hRqTa2m2k91prjv7Opb7vCD16zNhdB48hpLdleGLa9wXt6FsJzvoJZp8N7ADFcPQp8APoP
              96OyeNxCSq7JMoBPbCKB042G9Dlzsv0nOnK8a54KIWLao8/edsgIru/BXabqIAZoDaBgPM
              y8m8I/vTwy75woXkq+KmZaKIjPnagQWCQt0t1JmaDffjZysl9FwLPgkC0UL/+lmwP3rzNx
              j0CHEIpgWFLpi7d/kAniHO4sL4qVHz9uYvdLKD9Fj76eSPLUmNbqiqae5oDSH1mAEMciak
              NR9golDpPDmPw1SxRFseM6ZNDWLgK5nvYqNhFo6j32Jezr4Ynsab5oeZ8pvG+x+RYQIuxm
              mxzmLBysOnnm8YWGrsiBySm0WENm5tbMQ30bbahNo9X+2yHNAVb3+7DhjWDy4u7NJ2MWS9
              xQD1SbMDYiY5y+nqMSNAkDiD5nSYGbPyCqXEkgvpX0ro3p2iR2hr5+aETzZadNXLoz9DJu
              HP0GDqr1s3j2Dadtrn17bYMWG1oAoFYuac6wyfqCYVzo8pOSZ3lWBRqqTsZVdNASLlegJn
              pCgGvxprAKhhU6/d0dAAABAFgud/Gg2PK9Z43n2iynEB9il8fbgY4qua5/3fWhcBEiwft1
              tXpLxi6rB6K2yRyAY36JuvBdqqofFpTk+yVGxEsq0t+lXjKWl71C3DlamvmEmALqsBjUy1
              zAd6cgVu3pOB8SYH5sLXB1Uw8HQt32CEyLcSrpnpX+jc+oVlBnKTBkmtvRM0jzX5WiPyr6
              ASqiTbKWmh7NHdNxP2PoCz7OOvhge4aC+GvspYMQtwl4wP3wnuheNFU3X50zyiQ87UrNH1
              06E+Mrh4yyxg0nsap/ZuoGNbPe+EjcZlLKeET/lui3uLhOXTrmazE5geH8tKaGCtrfPYTU
              JpnzIM/e28gCqO0AAAEBANo3FZph7Emykej54UNTDUD5nmtZMX/3epolkgILFonwd3eew8
              TzLJzFPqkhcz+v/NfK4bCAQBgVWPkqfKYBPql6p69I7UF9Ono1udlyUAVIakdB0vpj9gbf
              0/hG+dP4aIkFzS139fsu8uvPV9ikVCda3b7ZJq4gTySkYPyfZkHaA1V3aboxxIrYdYvfO2
              2CKNa4KPvsxjCJiEz8j6Tv8ZHHg262055N8Zem+D11uSQYPpZLpnZogOSos/FZ0Q0du7hj
              q7jenPoyR5jaG8zAaA8jQ1wyz8LQnokEGroKiD29PZp4QRQF+LiXJrEUhLHM+XGdM8RM3Q
              g4ZuZ1uOjX+GsAAAEBANDuA8h7LQjN1/q1miRNdyddM56T9gH+cdM7pUkCvJMsSWu6Htqi
              Ldd0MLBbhj6hOwxdSh3IZ3DFFx76VYAc+68oVY3tkboYctmY42IbT/BtZjsAEURtWTjD1I
              VtdOdAnOkrrttq8HD6l9O2tNimZddDxfIm0dTO6sX37RMzy3yE9RzYaBh45uXlPfUoOwo9
              kzGXYKbO7dZ0If1KkL0RH9C5JxbNaZZrD2qH8ls9Zk4UBxC+BPTC9WqEpFmeLqXxnCZoGV
              G5yMCCpXoQBhfuNXQ90RkvRYHxM+gkK3IjPCd0MZkH5NjwfY+0IYJw1aHVPrAm9Z8I6gnI
              nM6hPbqH1fZL4lGT8AAABABVbttIlHnRzBLdP+OtN3DwhhRxZnBxdI8UKKtTPTDwNxzHQe
              10dFmsh3fJgfJw+YoIf9nW8+1pW4d5cbK8uOF7KuDqe8H6FYmNZH93uv6qBaVx0+9jWY5A
              WgYthJECpHOs2w8DbITl/qRYK+ppF7ro0xPxnbp6Ed8y3YdeyYk0UsLDbWVw68cVg77IgM
              a+5b6ueS/yJ9gX9AfWgg8MmTIXKxsHfPOEwWaW8+pJu9W0LeIkmb2OkAXe/m1gXp30pNOD
              qWhF2ONtn1Hhz9gIhKDkOlHnD7hbB3gH5cZ/DdT1APMmrjD8LqT7Bo1MO0JWUI9elcHkb6
              0p8Cv9Kg66gVgEX8Vm/pk0zRpEu63O8puNdEr8u0Fdu41dUNFb8cCXXInWqrvG8g3bd1eW
              R+ntjqz+d5emDqP92Xrb6Dg1KxZ1ah0W+h9lt0HSWQ6GgAAAAEBA8WUkHndO08NZ0XzmNP
              7B8MT4VOBt0d9KDwd94KQyeztMmS/NLoQNWg3ddu1TbPO4L5cQTFgoIkl8u9bFbD4QYZB0
              i0o1Iwx8LDXqITNlfOOnUMu+6t5c1TnQ7aPh7F9Y1RdsLf5AkYNlYKiP/v2vBVDREZsT5t
              D48/O0od0hL9IPeU41gC17nvLmo7W1V9Y5Q0n8l2WoQRws+pQiKkcnERfEjQ6ynTBGkk1t
              0GxsoKnNAnPL73wrZJ1RAhUlKSKxwB6bAaM6hG/5MXEYF9+dWWG/5KfxDhffF8Ri+l47T8
              Qe/0/GmLo4IPSwAAAAFBfnU6kRfYVpYWk1TQ0lUMFdUWEhIS3paWlRQUFNGY2hFcyJvbWV
              jTXNBMjNTcy4M8gkDgMAgICBgUEAEEAIAAACgMAL2lhbG96YWxhbW5hdXRpb24uZXh0LmN
              vbXAvbnVmZm9yYWh0YW5hbWVyaG9tZS9zZWxkZXJzd3BmcHNvZnNhbm1lc3RhY2luY2U=
              -----END OPENSSH PRIVATE KEY-----"
            SSH_USER: "Pc Lenovo"
            SERVER_IP: 192.168.18.168

        run: |
          env
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          # Actualizar contenedor
          ssh -i ~/.ssh/id_rsa $SSH_USER@$SERVER_IP "cd 'C:\Users\Pc Lenovo\OneDrive - Estudiantes ITCR\TEC\II Semestre 2024\Diseño\Proyecto\ProyectoDiseno\Healthphone\Docker' && docker-compose pull && docker-compose up -d"

